using MimeType.Core.Models;
using System;
using System.Collections.Immutable;

namespace MimeType.Services
{
    /// <summary>
    /// Provides a lazy-initialized set of MIME types and their associated extensions.
    /// 
    /// Supported MIME types and extensions (partial list; see full list in code):
    /// - application/json: .json
    /// - application/pdf: .pdf
    /// - application/zip: .zip
    /// - audio/mpeg: .mp3, .mp2, .m2a, .m3a, .mpga
    /// - audio/ogg: .oga, .ogg, .spx
    /// - image/jpeg: .jpg, .jpeg, .jpe, .jfif
    /// - image/pngjfif-tbnl .png
    /// - image/gif: .gif
    /// - text/html: .htm, .html
    /// - text/plain: .txt, .conf, .def, .diff, .in, .ksh, .list, .log, .pl
    /// - video/mp4: .mp4, .mp4v, .mpg4
    /// 
    /// Reference: https://mimetype.io/all-types
    /// Note: This is a large list; only a subset is shown above for brevity.
    /// </summary>
    public class BuiltInMimeTypes
    {
        private static readonly Lazy<ImmutableHashSet<MimeTypeModel>> _mimeTypes =
        new(LoadMimeTypes, isThreadSafe: true);

        public static ImmutableHashSet<MimeTypeModel> MimeTypes => _mimeTypes.Value;
        //https://mimetype.io/all-types
        private static ImmutableHashSet<MimeTypeModel> LoadMimeTypes()
        {
            return
            [
                new MimeTypeModel("application/andrew-inset", ".ez"),
                new MimeTypeModel("application/applixware", ".aw"),
                new MimeTypeModel("application/atom+xml", ".atom"),
                new MimeTypeModel("application/atomcat+xml", ".atomcat"),
                new MimeTypeModel("application/atomsvc+xml", ".atomsvc"),
                new MimeTypeModel("application/ccxml+xml", ".ccxml"),
                new MimeTypeModel("application/cu-seeme", ".cu"),
                new MimeTypeModel("application/davmount+xml", ".davmount"),
                new MimeTypeModel("application/ecmascript", ".ecma"),
                new MimeTypeModel("application/emma+xml", ".emma"),
                new MimeTypeModel("application/epub+zip", ".epub"),
                new MimeTypeModel("application/font-tdpfr", ".pfr"),
                new MimeTypeModel("application/gzip", ".gz", ".tgz"),
                new MimeTypeModel("application/hyperstudio", ".stk"),
                new MimeTypeModel("application/java-archive", ".jar"),
                new MimeTypeModel("application/java-serialized-object", ".ser"),
                new MimeTypeModel("application/java-vm", ".class"),
                new MimeTypeModel("application/json", ".json"),
                new MimeTypeModel("application/lost+xml", ".lostxml"),
                new MimeTypeModel("application/mac-binhex40", ".hqx"),
                new MimeTypeModel("application/mac-compactpro", ".cpt"),
                new MimeTypeModel("application/marc", ".mrc"),
                new MimeTypeModel("application/mathematica", ".ma", ".mb", ".nb"),
                new MimeTypeModel("application/mathml+xml", ".mathml", ".mml"),
                new MimeTypeModel("application/mbox", ".mbox"),
                new MimeTypeModel("application/mediaservercontrol+xml", ".mscml"),
                new MimeTypeModel("application/mp4", ".mp4s"),
                new MimeTypeModel("application/msword", ".doc", ".dot", ".wiz"),
                new MimeTypeModel("application/mxf", ".mxf"),
                new MimeTypeModel("application/octet-stream", ".a", ".bin", ".bpk", ".deploy", ".dist", ".distz", ".dmg", ".dms", ".dump", ".elc", ".lha", ".lrf", ".lzh", ".o", ".obj", ".pkg", ".so"),
                new MimeTypeModel("application/oda", ".oda"),
                new MimeTypeModel("application/oebps-package+xml", ".opf"),
                new MimeTypeModel("application/ogg", ".ogx"),
                new MimeTypeModel("application/onenote", ".onepkg", ".onetmp", ".onetoc", ".onetoc2"),
                new MimeTypeModel("application/patch-ops-error+xml", ".xer"),
                new MimeTypeModel("application/pdf", ".pdf"),
                new MimeTypeModel("application/pgp-encrypted", ".pgp"),
                new MimeTypeModel("application/pgp-signature", ".asc", ".sig"),
                new MimeTypeModel("application/pics-rules", ".prf"),
                new MimeTypeModel("application/pkcs10", ".p10"),
                new MimeTypeModel("application/pkcs7-mime", ".p7c", ".p7m"),
                new MimeTypeModel("application/pkcs7-signature", ".p7s"),
                new MimeTypeModel("application/pkix-cert", ".cer"),
                new MimeTypeModel("application/pkix-crl", ".crl"),
                new MimeTypeModel("application/pkix-pkipath", ".pkipath"),
                new MimeTypeModel("application/pkixcmp", ".pki"),
                new MimeTypeModel("application/pls+xml", ".pls"),
                new MimeTypeModel("application/postscript", ".ai", ".eps", ".ps"),
                new MimeTypeModel("application/prql", ".prql"),
                new MimeTypeModel("application/prs.cww", ".cww"),
                new MimeTypeModel("application/rdf+xml", ".rdf"),
                new MimeTypeModel("application/reginfo+xml", ".rif"),
                new MimeTypeModel("application/relax-ng-compact-syntax", ".rnc"),
                new MimeTypeModel("application/resource-lists+xml", ".rl"),
                new MimeTypeModel("application/resource-lists-diff+xml", ".rld"),
                new MimeTypeModel("application/rls-services+xml", ".rs"),
                new MimeTypeModel("application/rsd+xml", ".rsd"),
                new MimeTypeModel("application/rss+xml", ".rss", ".xml"),
                new MimeTypeModel("application/rtf", ".rtf"),
                new MimeTypeModel("application/sbml+xml", ".sbml"),
                new MimeTypeModel("application/scvp-cv-request", ".scq"),
                new MimeTypeModel("application/scvp-cv-response", ".scs"),
                new MimeTypeModel("application/scvp-vp-request", ".spq"),
                new MimeTypeModel("application/scvp-vp-response", ".spp"),
                new MimeTypeModel("application/sdp", ".sdp"),
                new MimeTypeModel("application/set-payment-initiation", ".setpay"),
                new MimeTypeModel("application/set-registration-initiation", ".setreg"),
                new MimeTypeModel("application/shf+xml", ".shf"),
                new MimeTypeModel("application/smil+xml", ".smi", ".smil"),
                new MimeTypeModel("application/sparql-query", ".rq"),
                new MimeTypeModel("application/sparql-results+xml", ".srx"),
                new MimeTypeModel("application/srgs", ".gram"),
                new MimeTypeModel("application/srgs+xml", ".grxml"),
                new MimeTypeModel("application/ssml+xml", ".ssml"),
                new MimeTypeModel("application/vnd.3gpp.pic-bw-large", ".plb"),
                new MimeTypeModel("application/vnd.3gpp.pic-bw-small", ".psb"),
                new MimeTypeModel("application/vnd.3gpp.pic-bw-var", ".pvb"),
                new MimeTypeModel("application/vnd.3gpp2.tcap", ".tcap"),
                new MimeTypeModel("application/vnd.3m.post-it-notes", ".pwn"),
                new MimeTypeModel("application/vnd.accpac.simply.aso", ".aso"),
                new MimeTypeModel("application/vnd.accpac.simply.imp", ".imp"),
                new MimeTypeModel("application/vnd.acucobol", ".acu"),
                new MimeTypeModel("application/vnd.acucorp", ".acutc", ".atc"),
                new MimeTypeModel("application/vnd.adobe.air-application-installer-package+zip", ".air"),
                new MimeTypeModel("application/vnd.adobe.xdp+xml", ".xdp"),
                new MimeTypeModel("application/vnd.adobe.xfdf", ".xfdf"),
                new MimeTypeModel("application/vnd.airzip.filesecure.azf", ".azf"),
                new MimeTypeModel("application/vnd.airzip.filesecure.azs", ".azs"),
                new MimeTypeModel("application/vnd.amazon.ebook", ".azw"),
                new MimeTypeModel("application/vnd.americandynamics.acc", ".acc"),
                new MimeTypeModel("application/vnd.amiga.ami", ".ami"),
                new MimeTypeModel("application/vnd.android.package-archive", ".apk"),
                new MimeTypeModel("application/vnd.anser-web-certificate-issue-initiation", ".cii"),
                new MimeTypeModel("application/vnd.anser-web-funds-transfer-initiation", ".fti"),
                new MimeTypeModel("application/vnd.antix.game-component", ".atx"),
                new MimeTypeModel("application/vnd.apple.installer+xml", ".mpkg"),
                new MimeTypeModel("application/vnd.arastra.swi", ".swi"),
                new MimeTypeModel("application/vnd.audiograph", ".aep"),
                new MimeTypeModel("application/vnd.blueice.multipass", ".mpm"),
                new MimeTypeModel("application/vnd.bmi", ".bmi"),
                new MimeTypeModel("application/vnd.businessobjects", ".rep"),
                new MimeTypeModel("application/vnd.chemdraw+xml", ".cdxml"),
                new MimeTypeModel("application/vnd.chipnuts.karaoke-mmd", ".mmd"),
                new MimeTypeModel("application/vnd.cinderella", ".cdy"),
                new MimeTypeModel("application/vnd.claymore", ".cla"),
                new MimeTypeModel("application/vnd.clonk.c4group", ".c4d", ".c4f", ".c4g", ".c4p", ".c4u"),
                new MimeTypeModel("application/vnd.commonspace", ".csp"),
                new MimeTypeModel("application/vnd.contact.cmsg", ".cdbcmsg"),
                new MimeTypeModel("application/vnd.cosmocaller", ".cmc"),
                new MimeTypeModel("application/vnd.crick.clicker", ".clkx"),
                new MimeTypeModel("application/vnd.crick.clicker.keyboard", ".clkk"),
                new MimeTypeModel("application/vnd.crick.clicker.palette", ".clkp"),
                new MimeTypeModel("application/vnd.crick.clicker.template", ".clkt"),
                new MimeTypeModel("application/vnd.crick.clicker.wordbank", ".clkw"),
                new MimeTypeModel("application/vnd.criticaltools.wbs+xml", ".wbs"),
                new MimeTypeModel("application/vnd.ctc-posml", ".pml"),
                new MimeTypeModel("application/vnd.cups-ppd", ".ppd"),
                new MimeTypeModel("application/vnd.curl.car", ".car"),
                new MimeTypeModel("application/vnd.curl.pcurl", ".pcurl"),
                new MimeTypeModel("application/vnd.data-vision.rdz", ".rdz"),
                new MimeTypeModel("application/vnd.debian.binary-package", ".deb", ".udeb"),
                new MimeTypeModel("application/vnd.denovo.fcselayout-link", ".fe_launch"),
                new MimeTypeModel("application/vnd.dna", ".dna"),
                new MimeTypeModel("application/vnd.dolby.mlp", ".mlp"),
                new MimeTypeModel("application/vnd.dpgraph", ".dpg"),
                new MimeTypeModel("application/vnd.dreamfactory", ".dfac"),
                new MimeTypeModel("application/vnd.dynageo", ".geo"),
                new MimeTypeModel("application/vnd.ecowin.chart", ".mag"),
                new MimeTypeModel("application/vnd.enliven", ".nml"),
                new MimeTypeModel("application/vnd.epson.esf", ".esf"),
                new MimeTypeModel("application/vnd.epson.msf", ".msf"),
                new MimeTypeModel("application/vnd.epson.quickanime", ".qam"),
                new MimeTypeModel("application/vnd.epson.salt", ".slt"),
                new MimeTypeModel("application/vnd.epson.ssf", ".ssf"),
                new MimeTypeModel("application/vnd.eszigno3+xml", ".es3", ".et3"),
                new MimeTypeModel("application/vnd.ezpix-album", ".ez2"),
                new MimeTypeModel("application/vnd.ezpix-package", ".ez3"),
                new MimeTypeModel("application/vnd.fdf", ".fdf"),
                new MimeTypeModel("application/vnd.fdsn.mseed", ".mseed"),
                new MimeTypeModel("application/vnd.fdsn.seed", ".dataless", ".seed"),
                new MimeTypeModel("application/vnd.flographit", ".gph"),
                new MimeTypeModel("application/vnd.fluxtime.clip", ".ftc"),
                new MimeTypeModel("application/vnd.framemaker", ".book", ".fm", ".frame", ".maker"),
                new MimeTypeModel("application/vnd.frogans.fnc", ".fnc"),
                new MimeTypeModel("application/vnd.frogans.ltf", ".ltf"),
                new MimeTypeModel("application/vnd.fsc.weblaunch", ".fsc"),
                new MimeTypeModel("application/vnd.fujitsu.oasys", ".oas"),
                new MimeTypeModel("application/vnd.fujitsu.oasys2", ".oa2"),
                new MimeTypeModel("application/vnd.fujitsu.oasys3", ".oa3"),
                new MimeTypeModel("application/vnd.fujitsu.oasysgp", ".fg5"),
                new MimeTypeModel("application/vnd.fujitsu.oasysprs", ".bh2"),
                new MimeTypeModel("application/vnd.fujixerox.ddd", ".ddd"),
                new MimeTypeModel("application/vnd.fujixerox.docuworks", ".xdw"),
                new MimeTypeModel("application/vnd.fujixerox.docuworks.binder", ".xbd"),
                new MimeTypeModel("application/vnd.fuzzysheet", ".fzs"),
                new MimeTypeModel("application/vnd.genomatix.tuxedo", ".txd"),
                new MimeTypeModel("application/vnd.geogebra.file", ".ggb"),
                new MimeTypeModel("application/vnd.geogebra.tool", ".ggt"),
                new MimeTypeModel("application/vnd.geometry-explorer", ".gex", ".gre"),
                new MimeTypeModel("application/vnd.gerber", ".gbr"),
                new MimeTypeModel("application/vnd.gmx", ".gmx"),
                new MimeTypeModel("application/vnd.google-earth.kml+xml", ".kml"),
                new MimeTypeModel("application/vnd.google-earth.kmz", ".kmz"),
                new MimeTypeModel("application/vnd.grafeq", ".gqf", ".gqs"),
                new MimeTypeModel("application/vnd.groove-account", ".gac"),
                new MimeTypeModel("application/vnd.groove-help", ".ghf"),
                new MimeTypeModel("application/vnd.groove-identity-message", ".gim"),
                new MimeTypeModel("application/vnd.groove-injector", ".grv"),
                new MimeTypeModel("application/vnd.groove-tool-message", ".gtm"),
                new MimeTypeModel("application/vnd.groove-tool-template", ".tpl"),
                new MimeTypeModel("application/vnd.groove-vcard", ".vcg"),
                new MimeTypeModel("application/vnd.handheld-entertainment+xml", ".zmm"),
                new MimeTypeModel("application/vnd.hbci", ".hbci"),
                new MimeTypeModel("application/vnd.hhe.lesson-player", ".les"),
                new MimeTypeModel("application/vnd.hp-hpgl", ".hpgl"),
                new MimeTypeModel("application/vnd.hp-hpid", ".hpid"),
                new MimeTypeModel("application/vnd.hp-hps", ".hps"),
                new MimeTypeModel("application/vnd.hp-jlyt", ".jlt"),
                new MimeTypeModel("application/vnd.hp-pcl", ".pcl"),
                new MimeTypeModel("application/vnd.hp-pclxl", ".pclxl"),
                new MimeTypeModel("application/vnd.hydrostatix.sof-data", ".sfd-hdstx"),
                new MimeTypeModel("application/vnd.hzn-3d-crossword", ".x3d"),
                new MimeTypeModel("application/vnd.ibm.minipay", ".mpy"),
                new MimeTypeModel("application/vnd.ibm.modcap", ".afp", ".list3820", ".listafp"),
                new MimeTypeModel("application/vnd.ibm.rights-management", ".irm"),
                new MimeTypeModel("application/vnd.ibm.secure-container", ".sc"),
                new MimeTypeModel("application/vnd.iccprofile", ".icc", ".icm"),
                new MimeTypeModel("application/vnd.igloader", ".igl"),
                new MimeTypeModel("application/vnd.immervision-ivp", ".ivp"),
                new MimeTypeModel("application/vnd.immervision-ivu", ".ivu"),
                new MimeTypeModel("application/vnd.intercon.formnet", ".xpw", ".xpx"),
                new MimeTypeModel("application/vnd.intu.qbo", ".qbo"),
                new MimeTypeModel("application/vnd.intu.qfx", ".qfx"),
                new MimeTypeModel("application/vnd.ipunplugged.rcprofile", ".rcprofile"),
                new MimeTypeModel("application/vnd.irepository.package+xml", ".irp"),
                new MimeTypeModel("application/vnd.is-xpr", ".xpr"),
                new MimeTypeModel("application/vnd.jam", ".jam"),
                new MimeTypeModel("application/vnd.jcp.javame.midlet-rms", ".rms"),
                new MimeTypeModel("application/vnd.jisp", ".jisp"),
                new MimeTypeModel("application/vnd.joost.joda-archive", ".joda"),
                new MimeTypeModel("application/vnd.kahootz", ".ktr", ".ktz"),
                new MimeTypeModel("application/vnd.kde.karbon", ".karbon"),
                new MimeTypeModel("application/vnd.kde.kchart", ".chrt"),
                new MimeTypeModel("application/vnd.kde.kformula", ".kfo"),
                new MimeTypeModel("application/vnd.kde.kivio", ".flw"),
                new MimeTypeModel("application/vnd.kde.kontour", ".kon"),
                new MimeTypeModel("application/vnd.kde.kpresenter", ".kpr", ".kpt"),
                new MimeTypeModel("application/vnd.kde.kspread", ".ksp"),
                new MimeTypeModel("application/vnd.kde.kword", ".kwd", ".kwt"),
                new MimeTypeModel("application/vnd.kenameaapp", ".htke"),
                new MimeTypeModel("application/vnd.kidspiration", ".kia"),
                new MimeTypeModel("application/vnd.kinar", ".kne", ".knp"),
                new MimeTypeModel("application/vnd.koan", ".skd", ".skm", ".skp", ".skt"),
                new MimeTypeModel("application/vnd.kodak-descriptor", ".sse"),
                new MimeTypeModel("application/vnd.llamagraphics.life-balance.desktop", ".lbd"),
                new MimeTypeModel("application/vnd.llamagraphics.life-balance.exchange+xml", ".lbe"),
                new MimeTypeModel("application/vnd.lotus-1-2-3", ".123"),
                new MimeTypeModel("application/vnd.lotus-approach", ".apr"),
                new MimeTypeModel("application/vnd.lotus-freelance", ".pre"),
                new MimeTypeModel("application/vnd.lotus-notes", ".nsf"),
                new MimeTypeModel("application/vnd.lotus-organizer", ".org"),
                new MimeTypeModel("application/vnd.lotus-screencam", ".scm"),
                new MimeTypeModel("application/vnd.lotus-wordpro", ".lwp"),
                new MimeTypeModel("application/vnd.macports.portpkg", ".portpkg"),
                new MimeTypeModel("application/vnd.mcd", ".mcd"),
                new MimeTypeModel("application/vnd.medcalcdata", ".mc1"),
                new MimeTypeModel("application/vnd.mediastation.cdkey", ".cdkey"),
                new MimeTypeModel("application/vnd.mfer", ".mwf"),
                new MimeTypeModel("application/vnd.mfmp", ".mfm"),
                new MimeTypeModel("application/vnd.micrografx.flo", ".flo"),
                new MimeTypeModel("application/vnd.micrografx.igx", ".igx"),
                new MimeTypeModel("application/vnd.mif", ".mif"),
                new MimeTypeModel("application/vnd.mobius.daf", ".daf"),
                new MimeTypeModel("application/vnd.mobius.dis", ".dis"),
                new MimeTypeModel("application/vnd.mobius.mbk", ".mbk"),
                new MimeTypeModel("application/vnd.mobius.mqy", ".mqy"),
                new MimeTypeModel("application/vnd.mobius.msl", ".msl"),
                new MimeTypeModel("application/vnd.mobius.plc", ".plc"),
                new MimeTypeModel("application/vnd.mobius.txf", ".txf"),
                new MimeTypeModel("application/vnd.mophun.application", ".mpn"),
                new MimeTypeModel("application/vnd.mophun.certificate", ".mpc"),
                new MimeTypeModel("application/vnd.mozilla.xul+xml", ".xul"),
                new MimeTypeModel("application/vnd.ms-artgalry", ".cil"),
                new MimeTypeModel("application/vnd.ms-cab-compressed", ".cab"),
                new MimeTypeModel("application/vnd.ms-excel", ".xla", ".xlb", ".xlc", ".xlm", ".xls", ".xlt", ".xlw"),
                new MimeTypeModel("application/vnd.ms-excel.addin.macroenabled.12", ".xlam"),
                new MimeTypeModel("application/vnd.ms-excel.sheet.binary.macroenabled.12", ".xlsb"),
                new MimeTypeModel("application/vnd.ms-excel.sheet.macroenabled.12", ".xlsm"),
                new MimeTypeModel("application/vnd.ms-excel.template.macroenabled.12", ".xltm"),
                new MimeTypeModel("application/vnd.ms-fontobject", ".eot"),
                new MimeTypeModel("application/vnd.ms-htmlhelp", ".chm"),
                new MimeTypeModel("application/vnd.ms-ims", ".ims"),
                new MimeTypeModel("application/vnd.ms-lrm", ".lrm"),
                new MimeTypeModel("application/vnd.ms-pki.seccat", ".cat"),
                new MimeTypeModel("application/vnd.ms-pki.stl", ".stl"),
                new MimeTypeModel("application/vnd.ms-powerpoint", ".pot", ".ppa", ".pps", ".ppt", ".pwz"),
                new MimeTypeModel("application/vnd.ms-powerpoint.addin.macroenabled.12", ".ppam"),
                new MimeTypeModel("application/vnd.ms-powerpoint.presentation.macroenabled.12", ".pptm"),
                new MimeTypeModel("application/vnd.ms-powerpoint.slide.macroenabled.12", ".sldm"),
                new MimeTypeModel("application/vnd.ms-powerpoint.slideshow.macroenabled.12", ".ppsm"),
                new MimeTypeModel("application/vnd.ms-powerpoint.template.macroenabled.12", ".potm"),
                new MimeTypeModel("application/vnd.ms-project", ".mpp", ".mpt"),
                new MimeTypeModel("application/vnd.ms-word.document.macroenabled.12", ".docm"),
                new MimeTypeModel("application/vnd.ms-word.template.macroenabled.12", ".dotm"),
                new MimeTypeModel("application/vnd.ms-works", ".wcm", ".wdb", ".wks", ".wps"),
                new MimeTypeModel("application/vnd.ms-wpl", ".wpl"),
                new MimeTypeModel("application/vnd.ms-xpsdocument", ".xps"),
                new MimeTypeModel("application/vnd.mseq", ".mseq"),
                new MimeTypeModel("application/vnd.musician", ".mus"),
                new MimeTypeModel("application/vnd.muvee.style", ".msty"),
                new MimeTypeModel("application/vnd.neurolanguage.nlu", ".nlu"),
                new MimeTypeModel("application/vnd.noblenet-directory", ".nnd"),
                new MimeTypeModel("application/vnd.noblenet-sealer", ".nns"),
                new MimeTypeModel("application/vnd.noblenet-web", ".nnw"),
                new MimeTypeModel("application/vnd.nokia.n-gage.data", ".ngdat"),
                new MimeTypeModel("application/vnd.nokia.n-gage.symbian.install", ".n-gage"),
                new MimeTypeModel("application/vnd.nokia.radio-preset", ".rpst"),
                new MimeTypeModel("application/vnd.nokia.radio-presets", ".rpss"),
                new MimeTypeModel("application/vnd.novadigm.edm", ".edm"),
                new MimeTypeModel("application/vnd.novadigm.edx", ".edx"),
                new MimeTypeModel("application/vnd.novadigm.ext", ".ext"),
                new MimeTypeModel("application/vnd.oasis.opendocument.chart", ".odc"),
                new MimeTypeModel("application/vnd.oasis.opendocument.chart-template", ".otc"),
                new MimeTypeModel("application/vnd.oasis.opendocument.database", ".odb"),
                new MimeTypeModel("application/vnd.oasis.opendocument.formula", ".odf"),
                new MimeTypeModel("application/vnd.oasis.opendocument.formula-template", ".odft"),
                new MimeTypeModel("application/vnd.oasis.opendocument.graphics", ".odg"),
                new MimeTypeModel("application/vnd.oasis.opendocument.graphics-template", ".otg"),
                new MimeTypeModel("application/vnd.oasis.opendocument.image", ".odi"),
                new MimeTypeModel("application/vnd.oasis.opendocument.image-template", ".oti"),
                new MimeTypeModel("application/vnd.oasis.opendocument.presentation", ".odp"),
                new MimeTypeModel("application/vnd.oasis.opendocument.presentation-template", ".otp"),
                new MimeTypeModel("application/vnd.oasis.opendocument.spreadsheet", ".ods"),
                new MimeTypeModel("application/vnd.oasis.opendocument.spreadsheet-template", ".ots"),
                new MimeTypeModel("application/vnd.oasis.opendocument.text", ".odt"),
                new MimeTypeModel("application/vnd.oasis.opendocument.text-master", ".otm"),
                new MimeTypeModel("application/vnd.oasis.opendocument.text-template", ".ott"),
                new MimeTypeModel("application/vnd.oasis.opendocument.text-web", ".oth"),
                new MimeTypeModel("application/vnd.olpc-sugar", ".xo"),
                new MimeTypeModel("application/vnd.oma.dd2+xml", ".dd2"),
                new MimeTypeModel("application/vnd.openofficeorg.extension", ".oxt"),
                new MimeTypeModel("application/vnd.openxmlformats-officedocument.presentationml.presentation", ".pptx"),
                new MimeTypeModel("application/vnd.openxmlformats-officedocument.presentationml.slide", ".sldx"),
                new MimeTypeModel("application/vnd.openxmlformats-officedocument.presentationml.slideshow", ".ppsx"),
                new MimeTypeModel("application/vnd.openxmlformats-officedocument.presentationml.template", ".potx"),
                new MimeTypeModel("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", ".xlsx"),
                new MimeTypeModel("application/vnd.openxmlformats-officedocument.spreadsheetml.template", ".xltx"),
                new MimeTypeModel("application/vnd.openxmlformats-officedocument.wordprocessingml.document", ".docx"),
                new MimeTypeModel("application/vnd.openxmlformats-officedocument.wordprocessingml.template", ".dotx"),
                new MimeTypeModel("application/vnd.osgi.dp", ".dp"),
                new MimeTypeModel("application/vnd.palm", ".oprc", ".pdb", ".pqa"),
                new MimeTypeModel("application/vnd.pg.format", ".str"),
                new MimeTypeModel("application/vnd.pg.osasli", ".ei6"),
                new MimeTypeModel("application/vnd.picsel", ".efif"),
                new MimeTypeModel("application/vnd.pocketlearn", ".plf"),
                new MimeTypeModel("application/vnd.powerbuilder6", ".pbd"),
                new MimeTypeModel("application/vnd.previewsystems.box", ".box"),
                new MimeTypeModel("application/vnd.proteus.magazine", ".mgz"),
                new MimeTypeModel("application/vnd.publishare-delta-tree", ".qps"),
                new MimeTypeModel("application/vnd.pvi.ptid1", ".ptid"),
                new MimeTypeModel("application/vnd.quark.quarkxpress", ".qwd", ".qwt", ".qxb", ".qxd", ".qxl", ".qxt"),
                new MimeTypeModel("application/vnd.rar", ".rar"),
                new MimeTypeModel("application/vnd.recordare.musicxml", ".mxl"),
                new MimeTypeModel("application/vnd.recordare.musicxml+xml", ".musicxml"),
                new MimeTypeModel("application/vnd.rim.cod", ".cod"),
                new MimeTypeModel("application/vnd.rn-realmedia", ".rm"),
                new MimeTypeModel("application/vnd.route66.link66+xml", ".link66"),
                new MimeTypeModel("application/vnd.seemail", ".see"),
                new MimeTypeModel("application/vnd.sema", ".sema"),
                new MimeTypeModel("application/vnd.semd", ".semd"),
                new MimeTypeModel("application/vnd.semf", ".semf"),
                new MimeTypeModel("application/vnd.shana.informed.formdata", ".ifm"),
                new MimeTypeModel("application/vnd.shana.informed.formtemplate", ".itp"),
                new MimeTypeModel("application/vnd.shana.informed.interchange", ".iif"),
                new MimeTypeModel("application/vnd.shana.informed.package", ".ipk"),
                new MimeTypeModel("application/vnd.simtech-mindmapper", ".twd", ".twds"),
                new MimeTypeModel("application/vnd.smaf", ".mmf"),
                new MimeTypeModel("application/vnd.smart.teacher", ".teacher"),
                new MimeTypeModel("application/vnd.solent.sdkm+xml", ".sdkd", ".sdkm"),
                new MimeTypeModel("application/vnd.spotfire.dxp", ".dxp"),
                new MimeTypeModel("application/vnd.spotfire.sfs", ".sfs"),
                new MimeTypeModel("application/vnd.stardivision.calc", ".sdc"),
                new MimeTypeModel("application/vnd.stardivision.draw", ".sda"),
                new MimeTypeModel("application/vnd.stardivision.impress", ".sdd"),
                new MimeTypeModel("application/vnd.stardivision.math", ".smf"),
                new MimeTypeModel("application/vnd.stardivision.writer", ".sdw", ".vor"),
                new MimeTypeModel("application/vnd.stardivision.writer-global", ".sgl"),
                new MimeTypeModel("application/vnd.sun.xml.calc", ".sxc"),
                new MimeTypeModel("application/vnd.sun.xml.calc.template", ".stc"),
                new MimeTypeModel("application/vnd.sun.xml.draw", ".sxd"),
                new MimeTypeModel("application/vnd.sun.xml.draw.template", ".std"),
                new MimeTypeModel("application/vnd.sun.xml.impress", ".sxi"),
                new MimeTypeModel("application/vnd.sun.xml.impress.template", ".sti"),
                new MimeTypeModel("application/vnd.sun.xml.math", ".sxm"),
                new MimeTypeModel("application/vnd.sun.xml.writer", ".sxw"),
                new MimeTypeModel("application/vnd.sun.xml.writer.global", ".sxg"),
                new MimeTypeModel("application/vnd.sun.xml.writer.template", ".stw"),
                new MimeTypeModel("application/vnd.sus-calendar", ".sus", ".susp"),
                new MimeTypeModel("application/vnd.svd", ".svd"),
                new MimeTypeModel("application/vnd.symbian.install", ".sis", ".sisx"),
                new MimeTypeModel("application/vnd.syncml+xml", ".xsm"),
                new MimeTypeModel("application/vnd.syncml.dm+wbxml", ".bdm"),
                new MimeTypeModel("application/vnd.syncml.dm+xml", ".xdm"),
                new MimeTypeModel("application/vnd.tao.intent-module-archive", ".tao"),
                new MimeTypeModel("application/vnd.tmobile-livetv", ".tmo"),
                new MimeTypeModel("application/vnd.trid.tpt", ".tpt"),
                new MimeTypeModel("application/vnd.triscape.mxs", ".mxs"),
                new MimeTypeModel("application/vnd.trueapp", ".tra"),
                new MimeTypeModel("application/vnd.ufdl", ".ufd", ".ufdl"),
                new MimeTypeModel("application/vnd.uiq.theme", ".utz"),
                new MimeTypeModel("application/vnd.umajin", ".umj"),
                new MimeTypeModel("application/vnd.unity", ".unityweb"),
                new MimeTypeModel("application/vnd.uoml+xml", ".uoml"),
                new MimeTypeModel("application/vnd.vcx", ".vcx"),
                new MimeTypeModel("application/vnd.visio", ".vsd", ".vss", ".vst", ".vsw", ".vsdx", ".vssx", ".vstx", ".vssm", ".vstm"),
                new MimeTypeModel("application/vnd.visionary", ".vis"),
                new MimeTypeModel("application/vnd.vsf", ".vsf"),
                new MimeTypeModel("application/vnd.wap.sic", ".sic"),
                new MimeTypeModel("application/vnd.wap.slc", ".slc"),
                new MimeTypeModel("application/vnd.wap.wbxml", ".wbxml"),
                new MimeTypeModel("application/vnd.wap.wmlc", ".wmlc"),
                new MimeTypeModel("application/vnd.wap.wmlscriptc", ".wmlsc"),
                new MimeTypeModel("application/vnd.webturbo", ".wtb"),
                new MimeTypeModel("application/vnd.wordperfect", ".wpd"),
                new MimeTypeModel("application/vnd.wqd", ".wqd"),
                new MimeTypeModel("application/vnd.wt.stf", ".stf"),
                new MimeTypeModel("application/vnd.xara", ".xar"),
                new MimeTypeModel("application/vnd.xfdl", ".xfdl"),
                new MimeTypeModel("application/vnd.yamaha.hv-dic", ".hvd"),
                new MimeTypeModel("application/vnd.yamaha.hv-script", ".hvs"),
                new MimeTypeModel("application/vnd.yamaha.hv-voice", ".hvp"),
                new MimeTypeModel("application/vnd.yamaha.openscoreformat", ".osf"),
                new MimeTypeModel("application/vnd.yamaha.openscoreformat.osfpvg+xml", ".osfpvg"),
                new MimeTypeModel("application/vnd.yamaha.smaf-audio", ".saf"),
                new MimeTypeModel("application/vnd.yamaha.smaf-phrase", ".spf"),
                new MimeTypeModel("application/vnd.yellowriver-custom-menu", ".cmp"),
                new MimeTypeModel("application/vnd.zul", ".zir", ".zirz"),
                new MimeTypeModel("application/vnd.zzazz.deck+xml", ".zaz"),
                new MimeTypeModel("application/voicexml+xml", ".vxml"),
                new MimeTypeModel("application/wasm", ".wasm"),
                new MimeTypeModel("application/winhlp", ".hlp"),
                new MimeTypeModel("application/wsdl+xml", ".wsdl"),
                new MimeTypeModel("application/wspolicy+xml", ".wspolicy"),
                new MimeTypeModel("application/x-7z-compressed", ".7z"),
                new MimeTypeModel("application/x-abiword", ".abw", ".zabw", ".abw.gz"),
                new MimeTypeModel("application/x-ace-compressed", ".ace"),
                new MimeTypeModel("application/x-authorware-bin", ".aab", ".u32", ".vox", ".x32"),
                new MimeTypeModel("application/x-authorware-map", ".aam"),
                new MimeTypeModel("application/x-authorware-seg", ".aas"),
                new MimeTypeModel("application/x-bcpio", ".bcpio"),
                new MimeTypeModel("application/x-bittorrent", ".torrent"),
                new MimeTypeModel("application/x-bzip", ".bz"),
                new MimeTypeModel("application/x-bzip2", ".boz", ".bz2"),
                new MimeTypeModel("application/x-cdlink", ".vcd"),
                new MimeTypeModel("application/x-chat", ".chat"),
                new MimeTypeModel("application/x-chess-pgn", ".pgn"),
                new MimeTypeModel("application/x-cpio", ".cpio"),
                new MimeTypeModel("application/x-csh", ".csh"),
                new MimeTypeModel("application/x-debian-package", ".deb", ".udeb"),
                new MimeTypeModel("application/x-director", ".cct", ".cst", ".cxt", ".dcr", ".dir", ".dxr", ".fgd", ".swa", ".w3d"),
                new MimeTypeModel("application/x-doom", ".wad"),
                new MimeTypeModel("application/x-dtbncx+xml", ".ncx"),
                new MimeTypeModel("application/x-dtbook+xml", ".dtb"),
                new MimeTypeModel("application/x-dtbresource+xml", ".res"),
                new MimeTypeModel("application/x-dvi", ".dvi"),
                new MimeTypeModel("application/x-font-bdf", ".bdf"),
                new MimeTypeModel("application/x-font-ghostscript", ".gsf"),
                new MimeTypeModel("application/x-font-linux-psf", ".psf"),
                new MimeTypeModel("application/x-font-otf", ".otf"),
                new MimeTypeModel("application/x-font-pcf", ".pcf"),
                new MimeTypeModel("application/x-font-snf", ".snf"),
                new MimeTypeModel("application/x-font-ttf", ".ttc", ".ttf"),
                new MimeTypeModel("application/x-font-type1", ".afm", ".pfa", ".pfb", ".pfm"),
                new MimeTypeModel("application/x-futuresplash", ".spl"),
                new MimeTypeModel("application/x-gnumeric", ".gnumeric"),
                new MimeTypeModel("application/x-gtar", ".gtar"),
                new MimeTypeModel("application/x-gzip", ".gz", ".tgz"),
                new MimeTypeModel("application/x-hdf", ".hdf"),
                new MimeTypeModel("application/x-iso9660-image", ".iso", ".isoimg", ".cdr"),
                new MimeTypeModel("application/x-java-jnlp-file", ".jnlp"),
                new MimeTypeModel("application/x-killustrator", ".kil"),
                new MimeTypeModel("application/x-krita", ".kra", ".krz"),
                new MimeTypeModel("application/x-latex", ".latex"),
                new MimeTypeModel("application/x-mobipocket-ebook", ".mobi", ".prc"),
                new MimeTypeModel("application/x-ms-application", ".application"),
                new MimeTypeModel("application/x-ms-wmd", ".wmd"),
                new MimeTypeModel("application/x-ms-wmz", ".wmz"),
                new MimeTypeModel("application/x-ms-xbap", ".xbap"),
                new MimeTypeModel("application/x-msaccess", ".mdb"),
                new MimeTypeModel("application/x-msbinder", ".obd"),
                new MimeTypeModel("application/x-mscardfile", ".crd"),
                new MimeTypeModel("application/x-msclip", ".clp"),
                new MimeTypeModel("application/x-msdownload", ".bat", ".com", ".dll", ".exe", ".msi"),
                new MimeTypeModel("application/x-msmediaview", ".m13", ".m14", ".mvb"),
                new MimeTypeModel("application/x-msmetafile", ".wmf"),
                new MimeTypeModel("application/x-msmoney", ".mny"),
                new MimeTypeModel("application/x-mspublisher", ".pub"),
                new MimeTypeModel("application/x-msschedule", ".scd"),
                new MimeTypeModel("application/x-msterminal", ".trm"),
                new MimeTypeModel("application/x-mswrite", ".wri"),
                new MimeTypeModel("application/x-netcdf", ".cdf", ".nc"),
                new MimeTypeModel("application/x-perl", ".pm", ".pl"),
                new MimeTypeModel("application/x-pkcs12", ".p12", ".pfx"),
                new MimeTypeModel("application/x-pkcs7-certificates", ".p7b", ".spc"),
                new MimeTypeModel("application/x-pkcs7-certreqresp", ".p7r"),
                new MimeTypeModel("application/x-rar-compressed", ".rar"),
                new MimeTypeModel("application/x-redhat-package-manager", ".rpa"),
                new MimeTypeModel("application/x-rpm", ".rpm"),
                new MimeTypeModel("application/x-sh", ".sh"),
                new MimeTypeModel("application/x-shar", ".shar"),
                new MimeTypeModel("application/x-shellscript", ".sh"),
                new MimeTypeModel("application/x-shockwave-flash", ".swf"),
                new MimeTypeModel("application/x-silverlight-app", ".xap"),
                new MimeTypeModel("application/x-stuffit", ".sit"),
                new MimeTypeModel("application/x-stuffitx", ".sitx"),
                new MimeTypeModel("application/x-sv4cpio", ".sv4cpio"),
                new MimeTypeModel("application/x-sv4crc", ".sv4crc"),
                new MimeTypeModel("application/x-tar", ".tar"),
                new MimeTypeModel("application/x-tcl", ".tcl"),
                new MimeTypeModel("application/x-tex", ".tex"),
                new MimeTypeModel("application/x-tex-tfm", ".tfm"),
                new MimeTypeModel("application/x-texinfo", ".texi", ".texinfo"),
                new MimeTypeModel("application/x-ustar", ".ustar"),
                new MimeTypeModel("application/x-wais-source", ".src"),
                new MimeTypeModel("application/x-x509-ca-cert", ".crt", ".der"),
                new MimeTypeModel("application/x-xfig", ".fig"),
                new MimeTypeModel("application/x-xpinstall", ".xpi"),
                new MimeTypeModel("application/x-zip-compressed", ".zip"),
                new MimeTypeModel("application/xenc+xml", ".xenc"),
                new MimeTypeModel("application/xhtml+xml", ".xht", ".xhtml"),
                new MimeTypeModel("application/xml", ".xml", ".xpdl", ".xsl"),
                new MimeTypeModel("application/xml-dtd", ".dtd"),
                new MimeTypeModel("application/xop+xml", ".xop"),
                new MimeTypeModel("application/xslt+xml", ".xslt"),
                new MimeTypeModel("application/xspf+xml", ".xspf"),
                new MimeTypeModel("application/xv+xml", ".mxml", ".xhvml", ".xvm", ".xvml"),
                new MimeTypeModel("application/yaml", ".yaml", ".yml"),
                new MimeTypeModel("application/zip", ".zip"),
                new MimeTypeModel("application/zip-compressed", ".zip"),
                new MimeTypeModel("audio/3gpp2", ".3g2"),
                new MimeTypeModel("audio/aac", ".aac", ".m4a"),
                new MimeTypeModel("audio/aacp", ".aacp"),
                new MimeTypeModel("audio/adpcm", ".adp"),
                new MimeTypeModel("audio/aiff", ".aiff", ".aif", ".aff"),
                new MimeTypeModel("audio/x-aiff"),
                new MimeTypeModel("audio/basic", ".au", ".snd"),
                new MimeTypeModel("audio/flac", ".flac"),
                new MimeTypeModel("audio/midi", ".kar", ".mid", ".midi", ".rmi"),
                new MimeTypeModel("audio/mp4", ".mp4", ".m4a", ".m4b", ".m4p", ".m4r", ".m4v", ".mp4v", ".3gp", ".3g2", ".3ga", ".3gpa", ".3gpp", ".3gpp2", ".3gp2"),
                new MimeTypeModel("audio/mp4a-latm"),
                new MimeTypeModel("audio/mpeg", ".m2a", ".m3a", ".mp2", ".mp2a", ".mp3", ".mpga"),
                new MimeTypeModel("audio/ogg", ".oga", ".ogg", ".spx"),
                new MimeTypeModel("audio/opus", ".opus"),
                new MimeTypeModel("audio/vnd.digital-winds", ".eol"),
                new MimeTypeModel("audio/vnd.dts", ".dts"),
                new MimeTypeModel("audio/vnd.dts.hd", ".dtshd"),
                new MimeTypeModel("audio/vnd.lucent.voice", ".lvp"),
                new MimeTypeModel("audio/vnd.ms-playready.media.pya", ".pya"),
                new MimeTypeModel("audio/vnd.nuera.ecelp4800", ".ecelp4800"),
                new MimeTypeModel("audio/vnd.nuera.ecelp7470", ".ecelp7470"),
                new MimeTypeModel("audio/vnd.nuera.ecelp9600", ".ecelp9600"),
                new MimeTypeModel("audio/vnd.wav", ".wav"),
                new MimeTypeModel("audio/wav"),
                new MimeTypeModel("audio/x-wav"),
                new MimeTypeModel("audio/vnd.wave"),
                new MimeTypeModel("audio/wave"),
                new MimeTypeModel("audio/x-pn-wav"),
                new MimeTypeModel("audio/webm", ".weba"),
                new MimeTypeModel("audio/x-matroska", ".mka"),
                new MimeTypeModel("audio/x-mpegurl", ".m3u"),
                new MimeTypeModel("audio/x-ms-wax", ".wax"),
                new MimeTypeModel("audio/x-ms-wma", ".wma"),
                new MimeTypeModel("audio/x-pn-realaudio", ".ra", ".ram"),
                new MimeTypeModel("audio/x-pn-realaudio-plugin", ".rmp"),
                new MimeTypeModel("chemical/x-cdx", ".cdx"),
                new MimeTypeModel("chemical/x-cif", ".cif"),
                new MimeTypeModel("chemical/x-cmdf", ".cmdf"),
                new MimeTypeModel("chemical/x-cml", ".cml"),
                new MimeTypeModel("chemical/x-csml", ".csml"),
                new MimeTypeModel("chemical/x-xyz", ".xyz"),
                new MimeTypeModel("font/otf", ".otf"),
                new MimeTypeModel("font/woff", ".woff"),
                new MimeTypeModel("font/woff2", ".woff2"),
                new MimeTypeModel("gcode", ".gcode"),
                new MimeTypeModel("image/avif", ".avif"),
                new MimeTypeModel("image/avif-sequence", ".avifs"),
                new MimeTypeModel("image/bmp", ".bmp"),
                new MimeTypeModel("image/cgm", ".cgm"),
                new MimeTypeModel("image/g3fax", ".g3"),
                new MimeTypeModel("image/gif", ".gif"),
                new MimeTypeModel("image/heic", ".heif", ".heic"),
                new MimeTypeModel("image/ief", ".ief"),
                new MimeTypeModel("image/jxl", ".jxl"),
                new MimeTypeModel("image/jpeg", ".jpe", ".jpeg", ".jpg", ".pjpg", ".jfif", ".jfif-tbnl", ".jif"),
                new MimeTypeModel("image/pjpeg", ".jpe", ".jpeg", ".jpg", ".pjpg", ".jfi", ".jfif", ".jfif-tbnl", ".jif"),
                new MimeTypeModel("image/png", ".png"),
                new MimeTypeModel("image/prs.btif", ".btif"),
                new MimeTypeModel("image/svg+xml", ".svg", ".svgz"),
                new MimeTypeModel("image/tiff", ".tif", ".tiff"),
                new MimeTypeModel("image/vnd.adobe.photoshop", ".psd"),
                new MimeTypeModel("image/vnd.djvu", ".djv", ".djvu"),
                new MimeTypeModel("image/vnd.dwg", ".dwg"),
                new MimeTypeModel("image/vnd.dxf", ".dxf"),
                new MimeTypeModel("image/vnd.fastbidsheet", ".fbs"),
                new MimeTypeModel("image/vnd.fpx", ".fpx"),
                new MimeTypeModel("image/vnd.fst", ".fst"),
                new MimeTypeModel("image/vnd.fujixerox.edmics-mmr", ".mmr"),
                new MimeTypeModel("image/vnd.fujixerox.edmics-rlc", ".rlc"),
                new MimeTypeModel("image/vnd.ms-modi", ".mdi"),
                new MimeTypeModel("image/vnd.net-fpx", ".npx"),
                new MimeTypeModel("image/vnd.wap.wbmp", ".wbmp"),
                new MimeTypeModel("image/vnd.xiff", ".xif"),
                new MimeTypeModel("image/webp", ".webp"),
                new MimeTypeModel("image/x-adobe-dng", ".dng"),
                new MimeTypeModel("image/x-canon-cr2", ".cr2"),
                new MimeTypeModel("image/x-canon-crw", ".crw"),
                new MimeTypeModel("image/x-cmu-raster", ".ras"),
                new MimeTypeModel("image/x-cmx", ".cmx"),
                new MimeTypeModel("image/x-epson-erf", ".erf"),
                new MimeTypeModel("image/x-freehand", ".fh", ".fh4", ".fh5", ".fh7", ".fhc"),
                new MimeTypeModel("image/x-fuji-raf", ".raf"),
                new MimeTypeModel("image/x-icns", ".icns"),
                new MimeTypeModel("image/x-icon", ".ico"),
                new MimeTypeModel("image/x-kodak-dcr", ".dcr"),
                new MimeTypeModel("image/x-kodak-k25", ".k25"),
                new MimeTypeModel("image/x-kodak-kdc", ".kdc"),
                new MimeTypeModel("image/x-minolta-mrw", ".mrw"),
                new MimeTypeModel("image/x-nikon-nef", ".nef"),
                new MimeTypeModel("image/x-olympus-orf", ".orf"),
                new MimeTypeModel("image/x-panasonic-raw", ".raw", ".rw2", ".rwl"),
                new MimeTypeModel("image/x-pcx", ".pcx"),
                new MimeTypeModel("image/x-pentax-pef", ".pef", ".ptx"),
                new MimeTypeModel("image/x-pict", ".pct", ".pic"),
                new MimeTypeModel("image/x-portable-anymap", ".pnm"),
                new MimeTypeModel("image/x-portable-bitmap", ".pbm"),
                new MimeTypeModel("image/x-portable-graymap", ".pgm"),
                new MimeTypeModel("image/x-portable-pixmap", ".ppm"),
                new MimeTypeModel("image/x-rgb", ".rgb"),
                new MimeTypeModel("image/x-sigma-x3f", ".x3f"),
                new MimeTypeModel("image/x-sony-arw", ".arw"),
                new MimeTypeModel("image/x-sony-sr2", ".sr2"),
                new MimeTypeModel("image/x-sony-srf", ".srf"),
                new MimeTypeModel("image/x-xbitmap", ".xbm"),
                new MimeTypeModel("image/x-xpixmap", ".xpm"),
                new MimeTypeModel("image/x-xwindowdump", ".xwd"),
                new MimeTypeModel("message/rfc822", ".eml", ".mht", ".mhtml", ".mime", ".nws"),
                new MimeTypeModel("model/iges", ".iges", ".igs"),
                new MimeTypeModel("model/mesh", ".mesh", ".msh", ".silo"),
                new MimeTypeModel("model/vnd.dwf", ".dwf"),
                new MimeTypeModel("model/vnd.gdl", ".gdl"),
                new MimeTypeModel("model/vnd.gtw", ".gtw"),
                new MimeTypeModel("model/vnd.mts", ".mts"),
                new MimeTypeModel("model/vnd.vtu", ".vtu"),
                new MimeTypeModel("model/vrml", ".vrml", ".wrl"),
                new MimeTypeModel("test/mimetype", ".test"),
                new MimeTypeModel("test/mimetype/test"),
                new MimeTypeModel("text/calendar", ".ics", ".ifb"),
                new MimeTypeModel("text/css", ".css"),
                new MimeTypeModel("text/csv", ".csv"),
                new MimeTypeModel("text/html", ".htm", ".html"),
                new MimeTypeModel("text/javascript", ".js"),
                new MimeTypeModel("text/markdown", ".md", ".markdown", ".mdown", ".markdn"),
                new MimeTypeModel("text/mathml", ".mathml", ".mml"),
                new MimeTypeModel("text/plain", ".conf", ".def", ".diff", ".in", ".ksh", ".list", ".log", ".pl", ".text", ".txt"),
                new MimeTypeModel("text/prs.lines.tag", ".dsc"),
                new MimeTypeModel("text/richtext", ".rtx"),
                new MimeTypeModel("text/sgml", ".sgm", ".sgml"),
                new MimeTypeModel("text/tab-separated-values", ".tsv"),
                new MimeTypeModel("text/troff", ".man", ".me", ".ms", ".roff", ".t", ".tr"),
                new MimeTypeModel("text/uri-list", ".uri", ".uris", ".urls"),
                new MimeTypeModel("text/vnd.curl", ".curl"),
                new MimeTypeModel("text/vnd.curl.dcurl", ".dcurl"),
                new MimeTypeModel("text/vnd.curl.mcurl", ".mcurl"),
                new MimeTypeModel("text/vnd.curl.scurl", ".scurl"),
                new MimeTypeModel("text/vnd.fly", ".fly"),
                new MimeTypeModel("text/vnd.fmi.flexstor", ".flx"),
                new MimeTypeModel("text/vnd.graphviz", ".gv"),
                new MimeTypeModel("text/vnd.in3d.3dml", ".3dml"),
                new MimeTypeModel("text/vnd.in3d.spot", ".spot"),
                new MimeTypeModel("text/vnd.sun.j2me.app-descriptor", ".jad"),
                new MimeTypeModel("text/vnd.wap.si", ".si"),
                new MimeTypeModel("text/vnd.wap.sl", ".sl"),
                new MimeTypeModel("text/vnd.wap.wml", ".wml"),
                new MimeTypeModel("text/vnd.wap.wmlscript", ".wmls"),
                new MimeTypeModel("text/x-asm", ".asm", ".s"),
                new MimeTypeModel("text/x-c", ".c", ".cc", ".cpp", ".cxx", ".dic", ".h", ".hh"),
                new MimeTypeModel("text/x-fortran", ".f", ".f77", ".f90", ".for"),
                new MimeTypeModel("text/x-java-source", ".java"),
                new MimeTypeModel("text/x-pascal", ".p", ".pas", ".pp", ".inc"),
                new MimeTypeModel("text/x-python", ".py", ".pyc", ".pyo", ".pyd", ".whl"),
                new MimeTypeModel("text/x-setext", ".etx"),
                new MimeTypeModel("text/x-uuencode", ".uu"),
                new MimeTypeModel("text/x-vcalendar", ".vcs"),
                new MimeTypeModel("text/x-vcard", ".vcf"),
                new MimeTypeModel("video/3gpp", ".3gp"),
                new MimeTypeModel("video/3gpp2", ".3g2"),
                new MimeTypeModel("video/h261", ".h261"),
                new MimeTypeModel("video/h263", ".h263"),
                new MimeTypeModel("video/h264", ".h264"),
                new MimeTypeModel("video/jpeg", ".jpgv"),
                new MimeTypeModel("video/jpm", ".jpgm", ".jpm"),
                new MimeTypeModel("video/mj2", ".mj2", ".mjp2"),
                new MimeTypeModel("video/mp2t", ".ts"),
                new MimeTypeModel("video/mp4", ".mp4", ".mp4v", ".mpg4"),
                new MimeTypeModel("video/mpeg", ".m1v", ".m2v", ".mpa", ".mpe", ".mpeg", ".mpg"),
                new MimeTypeModel("video/ogg", ".ogv"),
                new MimeTypeModel("video/quicktime", ".mov", ".qt"),
                new MimeTypeModel("video/vnd.fvt", ".fvt"),
                new MimeTypeModel("video/vnd.mpegurl", ".m4u", ".mxu"),
                new MimeTypeModel("video/vnd.ms-playready.media.pyv", ".pyv"),
                new MimeTypeModel("video/vnd.vivo", ".viv"),
                new MimeTypeModel("video/webm", ".webm"),
                new MimeTypeModel("video/x-f4v", ".f4v"),
                new MimeTypeModel("video/x-fli", ".fli"),
                new MimeTypeModel("video/x-flv", ".flv"),
                new MimeTypeModel("video/x-m4v", ".m4v"),
                new MimeTypeModel("video/x-matroska", ".mkv"),
                new MimeTypeModel("video/x-ms-asf", ".asf", ".asx"),
                new MimeTypeModel("video/x-ms-wm", ".wm"),
                new MimeTypeModel("video/x-ms-wmv", ".wmv"),
                new MimeTypeModel("video/x-ms-wmx", ".wmx"),
                new MimeTypeModel("video/x-ms-wvx", ".wvx"),
                new MimeTypeModel("video/x-msvideo", ".avi"),
                new MimeTypeModel("video/x-sgi-movie", ".movie"),
                new MimeTypeModel("x-conference/x-cooltalk", ".ice"),
            ];
        }
    }
}